// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdouciiytknnbswfghiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkb3VjaWl5dGtubmJzd2ZnaGl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3OTUzOTAsImV4cCI6MjA3MDM3MTM5MH0.iYQFquxBRufiXk7mSbk_SVjxOYocEF_nJZYGXcb0N_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Create a service role client for admin operations (bypasses RLS)
export const supabaseAdmin = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, // You'll need to replace this with your service role key
  {
    auth: {
      autoRefreshToken: false,
      persistSession: false
    }
  }
);